version: '2.4' # 2.4 is the last version that supports depends_on conditions for service health
networks:
  cassandra:  # docker network where all cassandra nodes will be put in
services:
  cass1:
    image: cassandra:4.0   # better to use a specific version, if you want to control upgrades
    container_name: cass1
    hostname: cass1
    networks:
      - cassandra
    ports:
      - "7001:7000"  # Expose native binary CQL port for your apps
      - "19042:9042"
    volumes:
      - ./data/cass1:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
    healthcheck: &healthcheck
      test: "[ $$(ss -lH '( sport = :7000 )' | wc -l) -ne 0 ] || exit 1"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment: &environment    # Declare and save environments variables into "environment"
        CASSANDRA_SEEDS: "cass1"
        CASSANDRA_CLUSTER_NAME: InfiniSoft
        CASSANDRA_DC: Moscow
        CASSANDRA_RACK: First
        CASSANDRA_NUM_TOKENS: 16
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
